app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.checkrole'], function () {
	Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
	Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);

	Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
	Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
	Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
	Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);
	Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);

	Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
	Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
	Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
	Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
	Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);
	Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);

	Route::resource('orders', 'OrderController');
	Route::resource('cupoms', 'CupomsController');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
	Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
	Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
	Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});

Route::group(['middleware' => 'cors'], function(){

Route::post('oauth/access_token', function () {
	return Response::json(Authorizer::issueAccessToken());
});
});

Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => ['oauth','cors']], function () {
	Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
		Route::resource('order', 'Api\Client\ClientCheckoutController',
			['except' => ['create', 'edit', 'destroy']]
		);

		//\Codelivery\Http\Controllers\Api\Client\ClientCheckoutController
		Route::get('products', 'Api\Client\ClientProductController@index');

	});

	Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
		Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController',
				['except' => ['create', 'edit', 'destroy']]
		);
		Route::patch('order/{id}/update-status', [
				'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
				'as' => 'orders.update.status'
		]);
	});

	Route::get('authenticated', 'Api\UserController@authenticated');
	Route::get('cupom/{code}', 'Api\CupomController@show');
});

app/Http/Controllers/Api/CupomController.php
<?php namespace Codelivery\Http\Controllers\Api;

use Codelivery\Http\Controllers\Controller;
use Codelivery\Repositories\CupomRepository;
use Codelivery\Repositories\ProductRepository;

class CupomController extends Controller
{
    /**
     * @var ProductRepository
     */
    private $cupomRepository;

    public function __construct(CupomRepository $cupomRepository)
    {
        $this->cupomRepository = $cupomRepository;

    }

    public function show($code)
    {
        return $this->cupomRepository->skipPresenter(false)->findByCode($code);
    }

}

app/Http/Controllers/CupomsController.php
<?php

namespace Codelivery\Http\Controllers;

use Codelivery\Repositories\CategoryRepository;
use Codelivery\Repositories\CupomRepository;
use Illuminate\Http\Request;
use Codelivery\Http\Requests;
use Codelivery\Http\Controllers\Controller;
use Illuminate\Support\Facades\View;

class CupomsController extends Controller
{

    /**
     * @var CupomRepository
     */
    private $cupomRepository;

    public function __construct(CupomRepository $cupomRepository)
    {
        $this->cupomRepository = $cupomRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $cupoms = $this->cupomRepository->paginate(5);
        return view('admin.cupoms.index', ['cupoms' => $cupoms]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return View::make('admin.cupoms.create');
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Requests\AdminCupomRequest $request)
    {
        $data = $request->all();
        $this->cupomRepository->create($data);

        return redirect()->route('admin.admin.cupoms.index');


    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        $category = $this->categoryRepository->find($id);
        return View::make('admin.categories.edit', compact('category'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Requests\AdminCategoryRequest $request, $id)
    {
        $data = $request->all();
        $this->categoryRepository->update($data, $id);

        return redirect()->route('admin.categories.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/cupoms/create.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Novo Cupom</h3>
        @include('errors.check')
        {!! Form::open(['route' => 'admin.admin.cupoms.store']) !!}
            @include('admin.cupoms.form')
            <div class="form-group">
                {!! Form::submit('Criar Cupom', ['class' => 'btn btn-primary']) !!}
            </div>
        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/cupoms/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Editando Categoria: {{$category->name}}</h3>
        @include('errors.check')
        {!! Form::model($category, ['route' => ['admin.categories.update', $category->id], 'method' => 'put']) !!}
            @include('admin.categories.form')

            <div class="form-group">
                {!! Form::submit('Salvar Categoria', ['class' => 'btn btn-primary']) !!}
            </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/cupoms/form.blade.php
<div class="form-group">
    {!! Form::label('code', 'Codigo:') !!}
    {!! Form::text('code', null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('value', 'Valor:') !!}
    {!! Form::text('value', null, ['class' => 'form-control']) !!}
</div>

resources/views/admin/cupoms/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Cupoms</h3>
        <a href="{{route('admin.admin.cupoms.create')}}" class="btn btn-default">Nov Cupom</a>
        <br/>
        <br/>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>id</th>
                    <th>code</th>
                    <th>value</th>
                    <th>used</th>
                    <th>acao</th>
                </tr>
            </thead>
            <tbody>
                @foreach($cupoms as $cupom)
                    <tr>
                        <td>{!! $cupom->id !!}</td>
                        <td>{!! $cupom->code !!}</td>
                        <td>{!! $cupom->value !!}</td>
                        <td>{!! $cupom->used !!}</td>
                        <td><a href="{{route('admin.admin.cupoms.edit', ['id' => $cupom->id])}}" class="btn btn-default">editar</a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {!! $cupoms->render() !!}
    </div>
@endsection