app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.checkrole'], function () {
	Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
	Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);

	Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
	Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
	Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
	Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);
	Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);

	Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
	Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
	Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
	Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
	Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);
	Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);

	Route::resource('orders', 'OrderController');
	Route::resource('cupoms', 'CupomsController');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
	Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
	Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
	Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});

Route::group(['middleware' => 'cors'], function(){

Route::post('oauth/access_token', function () {
	return Response::json(Authorizer::issueAccessToken());
});
});

Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => ['oauth','cors']], function () {
	Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
		Route::resource('order', 'Api\Client\ClientCheckoutController',
			['except' => ['create', 'edit', 'destroy']]
		);

		//\Codelivery\Http\Controllers\Api\Client\ClientCheckoutController
		Route::get('products', 'Api\Client\ClientProductController@index');

	});

	Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
		Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController',
				['except' => ['create', 'edit', 'destroy']]
		);
		Route::patch('order/{id}/update-status', [
				'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
				'as' => 'orders.update.status'
		]);
	});

	Route::get('authenticated', 'Api\UserController@authenticated');
	Route::get('cupom/{code}', 'Api\CupomController@show');
});

app/Http/Controllers/OrderController.php
<?php namespace Codelivery\Http\Controllers;

use Codelivery\Repositories\OrderRepository;
use Codelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

use Codelivery\Http\Requests;
use Codelivery\Http\Controllers\Controller;

class OrderController extends Controller
{
    /**
     * @var OrderRepository
     */
    private $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->orderRepository->paginate();
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, UserRepository $userRepository)
    {
        $list_status = [
           0 => 'Pendente',
           1  => 'A caminho',
           2  => 'Entregue'
        ];

        $order = $this->orderRepository->find($id);

        $deliveryman = $userRepository->getDeliverymen();
        return view('admin.orders.edit', compact('order', 'list_status', 'deliveryman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->orderRepository->update($all, $id);

        return redirect()->route('admin.admin.orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/admin/orders/edit.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h2>Pedido: #{{$order->id}} - R${{$order->total}}</h2>
        <h3>Cliente: {{$order->client->user->name}}</h3>
        <h4>Data: {{$order->created_at}}</h4>

        <p>
            <b>Etregar em:</b> <br/>
            {{$order->client->address}} - {{$order->client->city}} - {{$order->client->state}}
        </p>
        @include('errors.check')
        {!! Form::model($order, ['route' => ['admin.admin.orders.update', $order->id], 'method' => 'put']) !!}
            @include('admin.orders.form')

            <div class="form-group">
                {!! Form::submit('Salvar Order', ['class' => 'btn btn-primary']) !!}
            </div>

        {!! Form::close() !!}
    </div>
@endsection

resources/views/admin/orders/form.blade.php
<div class="form-group">
    {!! Form::label('status', 'Status:') !!}
    {!! Form::select('status', $list_status, null, ['class' => 'form-control']) !!}
</div>

<div class="form-group">
    {!! Form::label('deliveryman_id', 'Entregador:') !!}
    {!! Form::select('user_deliverman_id', $deliveryman, null, ['class' => 'form-control']) !!}
</div>

resources/views/admin/orders/index.blade.php
@extends('app')

@section('content')
    <div class="container">
        <h3>Pedidos</h3>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Total</th>
                    <th>Data</th>
                    <th>Itens</th>
                    <th>Entregdor</th>
                    <th>Status</th>
                    <th>Ação</th>
                </tr>
            </thead>
            <tbody>
                @foreach($orders as $order)
                    <tr>
                        <td>#{!! $order->id !!}</td>
                        <td>{!! $order->total !!}</td>
                        <td>{!! $order->created_at !!}</td>
                        <td>
                            <ul>
                            @foreach($order->items as $item)
                                <li>{{$item->product->name}} - {{$item->product->name}}</li>
                            @endforeach
                            </ul>
                        </td>
                        <td>
                            @if($order->deliveryman)
                                {{$order->deliveryman->name}}
                            @else
                                --
                            @endif
                        </td>
                        <td>{{$order->status}}</td>
                        <td><a href="{{route('admin.admin.orders.edit', ['id' => $order->id])}}" class="btn btn-default">editar</a></td>
                    </tr>
                @endforeach
            </tbody>
        </table>

        {!! $orders->render() !!}
    </div>
@endsection