app/Http/routes.php
<?php
/*
|--------------------------------------------------------------------------
| Application Routes
|--------------------------------------------------------------------------
|
| Here is where you can register all of the routes for an application.
| It's a breeze. Simply tell Laravel the URIs it should respond to
| and give it the controller to call when that URI is requested.
|
*/
Route::group(['prefix' => 'admin', 'as' => 'admin.', 'middleware' => 'auth.checkrole'], function () {
	Route::get('categories', ['as' => 'categories.index', 'uses' => 'CategoriesController@index']);
	Route::get('categories/create', ['as' => 'categories.create', 'uses' => 'CategoriesController@create']);
	Route::get('categories/edit/{id}', ['as' => 'categories.edit', 'uses' => 'CategoriesController@edit']);
	Route::put('categories/update/{id}', ['as' => 'categories.update', 'uses' => 'CategoriesController@update']);
	Route::post('categories/store', ['as' => 'categories.store', 'uses' => 'CategoriesController@store']);

	Route::get('clients', ['as' => 'clients.index', 'uses' => 'ClientsController@index']);
	Route::get('clients/create', ['as' => 'clients.create', 'uses' => 'ClientsController@create']);
	Route::get('clients/edit/{id}', ['as' => 'clients.edit', 'uses' => 'ClientsController@edit']);
	Route::put('clients/update/{id}', ['as' => 'clients.update', 'uses' => 'ClientsController@update']);
	Route::post('clients/store', ['as' => 'clients.store', 'uses' => 'ClientsController@store']);

	Route::get('products', ['as' => 'products.index', 'uses' => 'ProductsController@index']);
	Route::get('products/create', ['as' => 'products.create', 'uses' => 'ProductsController@create']);
	Route::get('products/edit/{id}', ['as' => 'products.edit', 'uses' => 'ProductsController@edit']);
	Route::put('products/update/{id}', ['as' => 'products.update', 'uses' => 'ProductsController@update']);
	Route::get('products/destroy/{id}', ['as' => 'products.destroy', 'uses' => 'ProductsController@destroy']);
	Route::post('products/store', ['as' => 'products.store', 'uses' => 'ProductsController@store']);

	Route::resource('orders', 'OrderController');
	Route::resource('cupoms', 'CupomsController');
});

Route::group(['prefix' => 'customer', 'as' => 'customer.'], function () {
	Route::get('order', ['as' => 'order.index', 'uses' => 'CheckoutController@index']);
	Route::get('order/create', ['as' => 'order.create', 'uses' => 'CheckoutController@create']);
	Route::post('order/store', ['as' => 'order.store', 'uses' => 'CheckoutController@store']);
});

Route::group(['middleware' => 'cors'], function(){

Route::post('oauth/access_token', function () {
	return Response::json(Authorizer::issueAccessToken());
});
});

Route::group(['prefix' => 'api', 'as' => 'api.', 'middleware' => ['oauth','cors']], function () {
	Route::group(['prefix' => 'client', 'as' => 'client.', 'middleware' => 'oauth.checkrole:client'], function () {
		Route::resource('order', 'Api\Client\ClientCheckoutController',
			['except' => ['create', 'edit', 'destroy']]
		);

		//\Codelivery\Http\Controllers\Api\Client\ClientCheckoutController
		Route::get('products', 'Api\Client\ClientProductController@index');

	});

	Route::group(['prefix' => 'deliveryman', 'as' => 'deliveryman.', 'middleware' => 'oauth.checkrole:deliveryman'], function () {
		Route::resource('order', 'Api\Deliveryman\DeliverymanCheckoutController',
				['except' => ['create', 'edit', 'destroy']]
		);
		Route::patch('order/{id}/update-status', [
				'uses' => 'Api\Deliveryman\DeliverymanCheckoutController@updateStatus',
				'as' => 'orders.update.status'
		]);
	});

	Route::get('authenticated', 'Api\UserController@authenticated');
	Route::get('cupom/{code}', 'Api\CupomController@show');
});

app/Http/Controllers/OrderController.php
<?php namespace Codelivery\Http\Controllers;

use Codelivery\Repositories\OrderRepository;
use Codelivery\Repositories\UserRepository;
use Illuminate\Http\Request;

use Codelivery\Http\Requests;
use Codelivery\Http\Controllers\Controller;

class OrderController extends Controller
{
    /**
     * @var OrderRepository
     */
    private $orderRepository;

    public function __construct(OrderRepository $orderRepository)
    {
        $this->orderRepository = $orderRepository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $orders = $this->orderRepository->paginate();
        return view('admin.orders.index', compact('orders'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id, UserRepository $userRepository)
    {
        $list_status = [
           0 => 'Pendente',
           1  => 'A caminho',
           2  => 'Entregue'
        ];

        $order = $this->orderRepository->find($id);

        $deliveryman = $userRepository->getDeliverymen();
        return view('admin.orders.edit', compact('order', 'list_status', 'deliveryman'));
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        $all = $request->all();
        $this->orderRepository->update($all, $id);

        return redirect()->route('admin.admin.orders.index');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/customer/order/create.blade.php
@extends('app')
@section('content')
    <div class="container">
        <h3>Novo Pedido</h3>

        @include('errors.check')
        <div class="container">
            {!! Form::open(['route' => 'customer.order.store', 'class' => 'form']) !!}
                <div class="form-group">
                    <label for="total">Total: </label>
                    <p id="total"></p>
                    <a href="#" id="btnNewItem" class="btn btn-default">Novo Item</a>
                    <table class="table table-bordered">
                        <thead>
                        <tr>
                            <th>Produto</th>
                            <th>Quantidade</th>
                        </tr>
                        </thead>
                        <tbody>
                        <tr>
                            <td>
                                <select class="form-control" name="items[0][product_id]">
                                @foreach($products as $product)
                                        <option value="{{$product->id}}" data-price="{{$product->price}}">{{$product->name}} --- {{$product->price}}</option>
                                @endforeach
                                </select>
                            </td>
                            <td>
                                {!! Form::text('items[0][qtd]', 1, ['class' => 'form-control']) !!}
                            </td>
                        </tr>
                        </tbody>
                    </table>
                </div>
                <div class="form-group">
                    {!! Form::submit('Criar Pedido', ['class' => 'btn btn-primary']) !!}
                </div>
            {!! Form::close() !!}
        </div>
    </div>
@endsection

@section('post-script')
    <script>
        $("#btnNewItem").click(function () {
            var row = $('table tbody > tr:last'),
                newRow = row.clone(),
                length = $("table tbody tr").length;

            newRow.find('td').each(function () {
               var td = $(this),
                   input = td.find('input, select'),
                   name = input.attr('name');

                input.attr('name', name.replace((length - 1) + "", length + ""));

            });
            newRow.find('input').val(1);
            newRow.insertAfter(row);
            calculateTotal();
        });

        $(document.body).on('click', 'select', function () {
            calculateTotal();
        });

        $(document.body).on('blur', 'input[name*=qtd]', function () {
            calculateTotal();
        });

        function calculateTotal()
        {
            var total = 0,
                trLen = $('table tbody tr').length,
                tr = null, price, qtd;

            for (var i = 0; i < trLen; i++) {
                tr = $('table tbody tr').eq(i);
                price = tr.find(':selected').data('price');
                qtd = tr.find('input').val();
                total += price * qtd;
            }
            $('#total').html(total);
        }
    </script>
@endsection

resources/views/customer/order/index.blade.php
@extends('app')
@section('content')
    <div class="container">
        <h3>Meus Pedidos</h3>

        <a href="{{route('customer.order.create')}}" class="btn btn-default">Novo Pedido</a>
        <br><br>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Total</th>
                    <th>Status</th>
                </tr>
            </thead>
            <tbody>
            @foreach($orders as $order)
            <tr>
                <td>{{$order->id}}</td>
                <td>{{$order->total}}</td>
                <td>{{$order->status}}</td>
            </tr>
                @endforeach
            </tbody>
        </table>
        {!! $orders->render() !!}
    </div>
@endsection